# -*- coding: utf-8 -*-
"""First.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dVyXNO5cKbqhee-1x8dXoJaca-k7JD0_
"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import datasets,linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

data=datasets.load_iris()
df = pd.DataFrame(data=data.data, columns=data.feature_names)
df.head()

df_x=df.drop(['petal width (cm)'],axis=1)
df_y=df['petal width (cm)']

x_train,x_test,y_train,y_test=train_test_split(df_x,df_y,test_size=0.2,random_state=2)
print(x_train.shape)
print(x_test.shape)
print(df.shape)

model=linear_model.LinearRegression()
model.fit(x_train.values,y_train.values)
y_test=model.predict(x_test.values)
print(y_test)

print(mean_squared_error(y_test,y_train[0:30]))

# plt.scatter(x_train,y_train)
print(model.coef_)
print(model.intercept_)

print(model.predict([[4.7,3.2,1.3]]))