# -*- coding: utf-8 -*-
"""rock_vs_mine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PP0EMGMZLD0-cBiATwrWwSYUyyQyCqxK
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import sklearn

data=pd.read_csv('/content/Copy of sonar data.csv',header=None)

# data.head(10)
data.shape

x=data.drop(60,axis=1)
y=data[60]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,stratify=y,random_state=2)

print(x_train.shape)
print(x_test.shape)

model=LogisticRegression()

model.fit(x_train,y_train)

x_final=model.predict(x_train)
score=sklearn.metrics.accuracy_score(x_final,y_train)

print(score)

y_final=model.predict(x_test)
score_test=sklearn.metrics.accuracy_score(y_final,y_test)
print(score_test)

d_R=[[0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,0.1609,0.1582,0.2238,0.0645,0.0660,0.2273,0.3100,0.2999,0.5078,0.4797,0.5783,0.5071,0.4328,0.5550,0.6711,0.6415,0.7104,0.8080,0.6791,0.3857,0.1307,0.2604,0.5121,0.7547,0.8537,0.8507,0.6692,0.6097,0.4943,0.2744,0.0510,0.2834,0.2825,0.4256,0.2641,0.1386,0.1051,0.1343,0.0383,0.0324,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032]]
# d_np=np.asarray(d)
# d_re=d_np.reshape(1,-1)
d_M=[[0.0233,0.0394,0.0416,0.0547,0.0993,0.1515,0.1674,0.1513,0.1723,0.2078,0.1239,0.0236,0.1771,0.3115,0.4990,0.6707,0.7655,0.8485,0.9805,1.0000,1.0000,0.9992,0.9067,0.6803,0.5103,0.4716,0.4980,0.6196,0.7171,0.6316,0.3554,0.2897,0.4316,0.3791,0.2421,0.0944,0.0351,0.0844,0.0436,0.1130,0.2045,0.1937,0.0834,0.1502,0.1675,0.1058,0.1111,0.0849,0.0596,0.0201,0.0071,0.0104,0.0062,0.0026,0.0025,0.0061,0.0038,0.0101,0.0078,0.0006]]
temp=model.predict(d_R)


if temp=='M':
  print("mine")
else:
  print("Rock")

